# Generated by Django 5.2.12 on 2026-03-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_businessprofile_ngoprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurplusFoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_type', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('pickup_deadline', models.DateTimeField()),
                ('location', models.TextField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CLAIMED', 'Claimed'), ('EXPIRED', 'Expired'), ('PICKED_UP', 'Picked Up')], default='AVAILABLE', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_listings', to='accounts.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FoodClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='accounts.ngoprofile')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='food_flash.surplusfoodlisting')),
            ],
        ),
        migrations.AddIndex(
            model_name='surplusfoodlisting',
            index=models.Index(fields=['status', 'pickup_deadline'], name='food_flash__status_692336_idx'),
        ),
        migrations.AddIndex(
            model_name='surplusfoodlisting',
            index=models.Index(fields=['business'], name='food_flash__busines_90faef_idx'),
        ),
        migrations.AddIndex(
            model_name='foodclaim',
            index=models.Index(fields=['listing', 'ngo'], name='food_flash__listing_4d710a_idx'),
        ),
        migrations.AddIndex(
            model_name='foodclaim',
            index=models.Index(fields=['status'], name='food_flash__status_75ae8f_idx'),
        ),
    ]
