# Generated by Django 5.2.12 on 2026-03-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_businessprofile_ngoprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_waste', models.FloatField(default=0, help_text='Total waste logged in kg')),
                ('total_redistributed', models.FloatField(default=0, help_text='Total food redistributed in kg')),
                ('energy_generated', models.FloatField(default=0, help_text='Estimated electricity generated in kWh')),
                ('carbon_offset', models.FloatField(default=0, help_text='Estimated CO2 offset in kg')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.businessprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'period_start', 'period_end'], name='compliance__busines_c74890_idx')],
                'unique_together': {('business', 'period_start', 'period_end')},
            },
        ),
    ]
