# Generated by Django 5.2.12 on 2026-03-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_businessprofile_ngoprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Standard Coefficients', max_length=100)),
                ('biogas_per_kg', models.FloatField(default=0.04, help_text='m³ of biogas per kg of food waste')),
                ('electricity_per_m3_biogas', models.FloatField(default=2.0, help_text='kWh of electricity per m³ of biogas')),
                ('compost_per_kg', models.FloatField(default=0.3, help_text='kg of compost per kg of food waste')),
                ('co2_offset_per_kg', models.FloatField(default=2.5, help_text='kg of CO2 offset per kg of food waste')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_kg', models.FloatField()),
                ('waste_type', models.CharField(default='Mixed organic', max_length=100)),
                ('conversion_output', models.JSONField(blank=True, help_text='Snapshot of calculated metrics at the time of logging', null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to='accounts.businessprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'logged_at'], name='bio_convert_busines_b18aa3_idx')],
            },
        ),
    ]
